/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface RoiCalculator {
    }
}
declare global {
    interface HTMLRoiCalculatorElement extends Components.RoiCalculator, HTMLStencilElement {
    }
    var HTMLRoiCalculatorElement: {
        prototype: HTMLRoiCalculatorElement;
        new (): HTMLRoiCalculatorElement;
    };
    interface HTMLElementTagNameMap {
        "roi-calculator": HTMLRoiCalculatorElement;
    }
}
declare namespace LocalJSX {
    interface RoiCalculator {
    }
    interface IntrinsicElements {
        "roi-calculator": RoiCalculator;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "roi-calculator": LocalJSX.RoiCalculator & JSXBase.HTMLAttributes<HTMLRoiCalculatorElement>;
        }
    }
}
